singleQuote: false # the default
printWidth: 85
tabWidth: 4
experimentalTernaries: false # the default
bracketSameLine: false # the default
proseWrap: always
importOrder:
    [
        "^(react|react-dom(/.*)?|react-router-dom)$",
        "^@nestjs(/.*)?$|^mongoose$",
        "^@tanstack/react-query$|^[^@./].*$|^@mui/.*$",
        "^@hilma/.*$",
        "^@internal/.*$",
        "^(?!.*\\.scss$)^(\\.\\./.*$|\\./.*$)",
        "\\.scss$",
    ]
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"]

plugins:
    - prettier-plugin-css-order
    - "@trivago/prettier-plugin-sort-imports"

cssDeclarationSorterKeepOverrides: false
cssDeclarationSorterOrder: concentric-css
