name: Add Labels For Features

on:
    pull_request_target:
        types:
            - opened
            - edited
            - synchronize

permissions:
    pull-requests: read

jobs:
    add-labels:
        permissions:
            contents: read
            pull-requests: write
        runs-on: "self-hosted"
        steps:
            - uses: actions/labeler@v4
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  configuration-path: .github/labeler.yaml
