name: "PR Check"

on:
    pull_request:
        types:
            - opened
            - edited
            - synchronize

concurrency:
    group:
        ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    pr_title:
        name: "Validate Title"
        runs-on: "self-hosted"
        if:
            github.actor != 'dependabot[bot]' && (github.event.action == 'opened' ||
            github.event.changes.title)
        steps:
            - uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    label_regex:
        name: "Add label"
        runs-on: "self-hosted"
        needs: pr_title
        steps:
            - uses: Bhacaz/label-regex@v2.1
              with:
                  field: title
                  regex: ^chore\(.*(deps)\)|^(fix|hotfix|feat|refactor|docs|test)
                  lowercase: true
